version: 2

registries:
  github-hoivikaj:
    type: nuget-feed
    url: https://nuget.pkg.github.com/hoivikaj/index.json
    username: hoivikaj
    password: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: nuget
    directory: /backend
    registries:
      - github-hoivikaj
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
